server {
    listen 80;

    location /install.sh {
        root /usr/share/nginx/html;
        default_type text/plain;
        add_header Content-Disposition 'inline; filename="install.sh"';
        add_header Cache-Control 'no-cache, no-store, must-revalidate';
    }

    location /install.ps1 {
        root /usr/share/nginx/html;
        default_type text/plain;
        add_header Content-Disposition 'inline; filename="install.ps1"';
        add_header Cache-Control 'no-cache, no-store, must-revalidate';
    }

    location / {
        return 301 https://openagentcrm.sapheron.in$request_uri;
    }
}
